spring.application.name=products-api
server.port=8080
#este es el binding el canal de comunicacion con el nombre del topio
spring.cloud.stream.bindings.commands-out-0.destination=products.commands
#El tipo de objeto que se va a enviar
spring.cloud.stream.bindings.commands-out-0.contentType=application/json

#Se configura donde esta el servidor kafka, brokers intermediario kafka es un intermedario
#El puerto por defecto de kafka es el 9092
spring.cloud.stream.kafka.binder.brokers=localhost:9092