spring.application.name=products-api
server.port=8080
#este es el binding el canal de comunicacion con el nombre del topio
spring.cloud.stream.bindings.commands-out-0.destination=products.commands
#El tipo de objeto que se va a enviar
spring.cloud.stream.bindings.commands-out-0.contentType=application/json


#Estas configuraciones son para la entrada la respuesta que se va a recibir de kafka
#Es el metodo que va a estar escuchando para la respuesta de kafka
spring.cloud.function.definition=handleReplies

spring.cloud.stream.bindings.handleReplies-in-0.destination=products.replies
spring.cloud.stream.bindings.handleReplies-in-0.contentType=application/json
spring.cloud.stream.bindings.handleReplies-in-0.group=products-api
spring.cloud.stream.kafka.bindings.handleReplies-in-0.consumer.startOffset=latest

#Se configura donde esta el servidor kafka, brokers intermediario kafka es un intermedario

#Configuracion local
#El puerto por defecto de kafka es el 9092
#spring.cloud.stream.kafka.binder.brokers=localhost:9092

#Configuracion red de docker el puerto interno de kafka es 19092
spring.cloud.stream.kafka.binder.brokers=kafka:19092